version: "3"

services:

  autoscaling:
    image: autoscaling
    build: .
    container_name: autoscaling
    environment:
      - AUTO_SCALING_GROUP=web-app-asg
      - REGION=sa-east-1
      - ENV=prod
    expose:
      - "6000"
    ports:
      - "6000:6000"
