  
version: "3"

services:

  auto-scaling:
    image: auto-scaling
    build: .
    container_name: auto-scaling
    environment:
      - AUTO_SCALING_GROUP=web-app-asg
      - REGION=sa-east-1
      - ENV=prod
    expose:
      - "6000"
    ports:
      - "6000:6000"
